CREATE TABLE jobs (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `run` TEXT,
  `pending` TINYINT UNSIGNED DEFAULT '0',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);